version: '3.8'
services:
  app:
    image: nodejs2022-app
    build: ./
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/app/.
      - '/usr/app/node_modules'
    restart: always
    networks:
     - my_network
  postgres:
    image: nodejs2022-db
    build: ${BASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${BASE_URL}/pgdata:/var/lib/postgres/data
    restart: always
    networks:
     - my_network
volumes:
  pgdata:
networks:
   my_network:
     driver: bridge           